site_name: 肇院生存指南
site_url: https://baddyscience.github.io/zqu-guide/
site_author: baddyscience
site_description: >-
  肇院生存指南

repo_name: zqu-survival-guide
repo_url: https://github.com/baddyscience/zqu-guide

copyright: Copyright &copy; <a href="https://github.com/baddyscience/zqu-guide" target="_blank" rel="noopener noreferrer">baddyscience</a>

theme:
  name: material
  custom_dir: overrides
  extra_css:
    - Genericons/genericons.css
    - css/custom.css
  language: zh
  static_templates:
    - 404.html
  favicon: images/1.png
  apple-touch-icon-precomposed: images/1.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github



markdown_extensions:
  - markdown.extensions.smarty
  - markdown.extensions.extra
  - attr_list
  - md_in_html
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/baddyscience/zqu-guide/
  analytics:
    provider: google
    property: G-DKPQFR2HG4

nav:
  - Home: index.md
  - 好店点评:
      - 肯德基: "好店点评/kfc.md"
      - 东门兰州拉面: "好店点评/东门兰州拉面.md"
      - 捞喜餐厅: "好店点评/捞喜餐厅.md"
      - 崽崽嗦盅盅面: "好店点评/崽崽嗦盅盅面"
  - 宿舍评价:
      - 紫薇宛3: "宿舍评价/zw3.md"
      - 力行1: "宿舍评价/力行1栋.md"
      - 博学1: "宿舍评价/博学1.md"
  - 生活技巧:
      - 赶路: "生活技巧/bike.md"
      - 图书馆预约操作流程: "生活技巧/图书馆预约.md"
      - 军训事宜: "生活技巧/军训事宜.md"
  - 工具推荐:
      - typora: "工具推荐/typora.md"
      - 游戏串流: "工具推荐/游戏串流相关软件.md"
  - 竞赛事项:
      - 蓝桥杯: "竞赛事项/蓝桥杯.md"
      - 泰迪杯数据分析: "竞赛事项/泰迪数据分析.md"
      - 外研社国才杯: "竞赛事项/外研社国才杯.md"
  - 实验引导:
      - 大数据实验室: "实验引导/大数据实验室.md"
      - 软件应用基础实验室: "实验引导/软件应用基础实验室.md"
  - 公共选修:
      - 葡萄酒与生活: "课程内容/葡萄酒与生活.md"
  - 通识教育:
      - 中外音乐鉴赏: "课程内容/中外音乐鉴赏.md"
  - 体育项目: "课程内容/c.md"
  - 经济与管理学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 政法学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 教育科学学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 体育与健康学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 文学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 外国语学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 数学与统计学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 生命科学学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 机械与汽车工程学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 电子与电气工程学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 计算机科学与软件学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 环境与化学工程学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 食品与制药工程学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 旅游与历史学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 音乐学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 美术学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 工业设计学院:
      - 课程内容:
          - C: "课程内容/c.md"
      - 教学资源:
          - C: "教学资源/c.md"
  - 模板: "template/template.md"
  - 后记: "后记.md"

