name: ci

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip3 install -U -r requirements.txt

      - name: Build Documentation
        run: mkdocs build

      - name: Deploy Documentation
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://${GH_PAT}@github.com/${{ github.repository }}.git
          mkdocs gh-deploy --force
